status = [
  "docs",
  "FreeBSD PYTHON:3.7",
  "FreeBSD PYTHON:3.8",
  "lint",
  "Linux python:3.7-slim",
  "Linux python:3.8-slim",
  "Windows python:3.7-windowsservercore",
  "Windows python:3.8-windowsservercore",
  "macOS PYTHON:3.7.5",
  "macOS PYTHON:3.8.0",
  "pep517",
]

delete_merged_branches = true
