status = [
  "docs",
  "FreeBSD PYTHON:3.6",
  "FreeBSD PYTHON:3.7",
  "FreeBSD PYTHON:3.8",
  "lint",
  "Linux python:3.6-slim",
  "Linux python:3.7-slim",
  "Windows python:3.6-windowsservercore-1809",
  "Windows python:3.7-windowsservercore-1809",
  "macOS PYTHON:3.6.8",
  "macOS PYTHON:3.7.2",
  "pep517",
]

delete_merged_branches = true
